### PR TITLE
Describe dependency setup in README

### PR DESCRIPTION
**Pull request by f4lco**
As per #7, a contributor should find some instructions on how to get started with dependencies etc. in the README. Because one can simply use `treon` to execute treon with the changes in the source tree in place, I assume "treon-runner.py" counts as redundant?

### CODE REVIEW

**Comment by amit1rrr** [comment]
> I assume "treon-runner.py" counts as redundant

Yeah, safe to delete it.


The change looks good. I am just wondering if there is a way for users to quickly ascertain whether they are running treon from the source or the package installed via PyPI. In my development, I always make sure by editing the help message and running `treon help`

**Comment by amit1rrr** [comment]
I just figured it, running following should show the user their local workspace location.

```
pip list --local | grep treon
```

**Comment by f4lco** [comment]
That's a good idea. I simply use one of the shell builtins:

```
$ which treon
/path/to/my/venv/bin/treon
$ command -v treon
/path/to/my/venv/bin/treon
```
Do you prefer one over the other (in comparison to `pip list`)? I assume the shell builtin will be a bit quicker, and may account for shell trickery, such as messed up `$PATH`, or aliases. After all, just that `pip` knows about a package called treon, does not mean it is actually the one to execute.

**Comment by amit1rrr** [comment]
Actually `which treon` would return the same path irrespective of whether it's using treon from our source directory or treon installed via `pip install`

That's why I was trying to find a way to show the actual source code path.

**Comment by f4lco** [comment]
Yeah I just figured these two commands address very different mistakes. First you have to convince your shell to use the treon executable from the venv (my primary mistake), then the dependency must be installed in editable mode. I think it will not hurt to document both.

**Comment by amit1rrr** [comment]
Perfect! Thanks @f4lco, I merged it.

**Pull request merged**
